# Generated by Django 4.2.7 on 2023-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('calories', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CalorieResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal1', models.IntegerField()),
                ('meal2', models.IntegerField()),
                ('meal3', models.IntegerField()),
                ('goal1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Macros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carb1', models.IntegerField()),
                ('carb2', models.IntegerField()),
                ('carb3', models.IntegerField()),
                ('pro1', models.IntegerField()),
                ('pro2', models.IntegerField()),
                ('pro3', models.IntegerField()),
            ],
        ),
    ]
