# Generated by Django 4.2.7 on 2024-04-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieking', '0002_calorieresult_day1_calorieresult_month1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnerApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burnerquery', models.CharField(max_length=200)),
                ('burnedcalories', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
            ],
        ),
    ]
