# Generated by Django 4.2.7 on 2024-04-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieking', '0003_burnerapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month2', models.IntegerField(default=12)),
                ('day2', models.IntegerField(default=1)),
                ('year2', models.IntegerField(default=23)),
                ('goal2', models.IntegerField()),
                ('burn1', models.IntegerField()),
                ('burn2', models.IntegerField()),
                ('burn3', models.IntegerField()),
                ('burn4', models.IntegerField()),
                ('burn5', models.IntegerField()),
                ('burn6', models.IntegerField()),
                ('burn7', models.IntegerField()),
                ('burn8', models.IntegerField()),
                ('burn9', models.IntegerField()),
                ('burn10', models.IntegerField()),
            ],
        ),
    ]
